name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Clean cache
        run: bun pm cache clean

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile

      - name: Build package with Node.js
        run: |
          node ./node_modules/.bin/tsc
          node ./node_modules/.bin/vite build

      - name: Publish to npm with Bun
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: bun publish
