name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v3.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Clean cache
        run: bun pm cache clean

      - name: Remove node_modules
        run: rm -rf node_modules

      - run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: bun publish
